
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    name: Removing trailing whitespace
    exclude: 'README\.md'
  - id: end-of-file-fixer
    name: Checking EOF with newline
  - id: check-merge-conflict
    name: Checking for merge conflicts

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
    - id: flake8
      name: Running flake8
      additional_dependencies: [
        'flake8-literal==1.3.0',
        'flake8-warnings==0.4.0',
        'flake8-bugbear==23.1.20',
        'flake8-simplify==0.19.3',
        'flake8-import-order==0.18.2',
        'flake8-useless-assert==0.4.4',
        'flake8-comprehensions==3.10.1',
        'flake8-implicit-str-concat==0.4.0',
      ]
