name: Release VPN list

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Create VPN list
      run: |
        python ./py-vpngate-src/vpngate.py -u

    - name: Update VPN list release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: "VPN list for ${{ steps.date.outputs.date }}"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ./py-vpngate-src/.vpngate_cache
